###
# @name 블로그 채널 생성
POST {{baseURL}}/blog/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "blogname": "취미 블로그",
  "categoryList": ["등산"]
}

###
# @name 블로그 상세조회
GET {{baseURL}}/blog?blogpkey=5
Authorization: Bearer {{token}}

