###
# @name 블로그 게시물 작성
POST {{baseURL}}/blog/contents/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "blogcategorypkey": 3,
  "title": "테스트",
  "content": "<!DOCTYPE html><html>123</html>"
}

###
# @name 블로그 게시물 조회
GET {{baseURL}}/blog/contents/?ccode=20237131811721589
